### ISSUE TITLE
Build fails intermittently 

### ISSUE THREAD

**Issue by seichter** [ryanfb/homebrew-alicevision#1]
I was trying to build AliceVision through your cask. However, it fails somewhere throughout the build. I've attached the `--verbose` version of the build log. Any obvious oversights? I have CUDA installed and newest Web Driver but I guess at that stage it shouldn't be a problem.

[Log of `brew install --verbose`](https://github.com/ryanfb/homebrew-alicevision/files/2343288/build_av_log.txt)

**Comment by ryanfb** [comment]
Hi, I see the line:

    nvcc fatal   : The version ('90100') of the host compiler ('Apple clang') is not supported

This means you have a newer Xcode than CUDA supports. Unfortunately CUDA 9.2 only supports Xcode 9.2 so you'll need to download, install, and switch to Xcode 9.2. To get back to Xcode 9.2, what you can do is go to [Apple's Developer Downloads page](https://developer.apple.com/download/more/) (for which you'll need a free Apple developer account), then search for "Xcode 9.2", then install the Command Line Tools for Xcode 9.2 package for your OS version. After installing, run `sudo xcode-select --switch /Library/Developer/CommandLineTools` and then verify that `clang --version` shows `Apple LLVM version 9.0.0`. There some further instructions here: https://ryanfb.github.io/etc/2018/08/17/alicevision_and_meshroom_on_mac_os_x.html

Thanks for the report -- feel free to reopen and let me know if you have any further trouble.
