### ISSUE TITLE
os x configure - missing deps (non-CUDA)

### ISSUE THREAD

**Issue by jm3** [ryanfb/homebrew-alicevision#2]
uncertain if any of the missing deps complained about (Ghostscript, GLPK, ILOG, COIN, SOPLEX) are formulae that should be added as dependencies to the tap, or is this is just the normal ending state when trying to compile without a CUDA GPU.

 I know that Ghostscript is a brew formula (but maybe it wasn't strictly a required dependency).

([full build log](https://gist.github.com/jm3/616698b32d1995a6c7d2094d92c1d121))

```Last 15 lines from /Users/jm3/Library/Logs/Homebrew/alicevision/01.cmake:
-- Found Ghostscript: /usr/local/bin/gs
-- Found GLPK: /usr/local/lib/libglpk.dylib (Required is at least version "4.33")
-- Could NOT find ILOG (missing: ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR)
-- Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY)
-- Could NOT find SOPLEX (missing: SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR)
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
-- Configuring incomplete, errors occurred!
```

**Comment by ryanfb** [comment]
Thanks for the report - I think I'd need the full log from the AliceVision build step, e.g.

    See also "/tmp/alicevision-20180926-72616-pkpqce/AliceVision-2.0.0/build/CMakeFiles/CMakeOutput.log".

Since the output at the top level is truncated (`Last 15 lines from /Users/jm3/Library/Logs/Homebrew/alicevision/01.cmake:`).

If you're trying to build without CUDA installed, the failure is likely earlier up in the log due to the absence of CUDA.

**Comment by jm3** [comment]
@ryanfb understood. I didn't include `CMakeOutput.log` only because, while I did see that message, the file didn't exist, at least not at that path.

**Comment by ryanfb** [comment]
You may need to try with `brew install -vd ryanfb/alicevision/alicevision`. This should both enable verbose output, and drop you into the appropriate temp directory on a build error.

**Comment by jm3** [comment]
cool, thanks, didn't know that trick! re-ran and added the complete build output and contents of `CMakeOutput.log` to [the linked gist](https://gist.github.com/jm3/616698b32d1995a6c7d2094d92c1d121), and now, further back up the log, I see:

```
OpenMP not found.
-- BUILD_SHARED_LIBS ON
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE 
   CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.0")
CMake Error at src/CMakeLists.txt:676 (message):
  Failed to find CUDA (>= 7.0).
```

So that makes a little more sense. I'll close this!

**Comment by ryanfb** [comment]
Thanks - just to leave a signpost for others coming across this issue, the upstream issue for a non-CUDA-dependent AliceVision is alicevision/AliceVision#439.
